spring.config.activate.on-profile: docker

server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka

app.eureka-server: eureka