server:
  port: 7000
  error:
    include-message: always
  forward-headers-strategy: framework

app:
  eureka-server: localhost
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        products-out-0:
          destination: products
          content-type: application/json
          producer:
            required-groups: auditGroup
        recommendations-out-0:
          destination: recommendations
          content-type: application/json
          producer:
            required-groups: auditGroup
        reviews-out-0:
          destination: reviews
          content-type: application/json
          producer:
            required-groups: auditGroup
      kafka:
        binder:
          brokers: "localhost:9092"
  application:
    name: product-composite


spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    com.arcadag.productcompositeservice: DEBUG

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs


api:
  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

  product-composite:
    get-composite-product:
      description: Return a composite view of the specified product id
      notes: |
        # Normal response
        If the requested product id is found the method will return information regarding:
        1. Base product information
        1. Reviews
        1. Recommendations
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)
        
        # Expected partial and error responses
        In the following cases, only a partial response be created (used to simplify testing of error conditions)
        
        ## Product id 113
        200 - Ok, but no recommendations will be returned
        
        ## Product id 213
        200 - Ok, but no reviews will be returned
        
        ## Non numerical product id
        400 - A **Bad Request** error will be returned
        
        ## Product id 13
        404 - A **Not Found** error will be returned
        
        ## Negative product ids
        422 - An **Unprocessable Entity** error will be returned

    create-composite-product:
      description: Creates a composite product
      notes: |
        # Normal response
        The composite product information posted to the API will be split up and stored as separate product-info, recommendation and review entities.

        # Expected error responses
        1. If a product with the same productId as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned

    delete-composite-product:
      description: Deletes a product composite
      notes: |
        # Normal response
        Entities for product information, recommendations and reviews related to the specified productId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.

        This means that a delete request of a non-existing product will return **200 Ok**.



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

