server:
  port: 7001
  error:
    include-message: always

spring:
  jpa:
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        massageProcessor-id-0:
          destination: products
          group: productGroup
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    com.arcadag.productservice: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"