spring.config.activate.on-profile: docker
server.port: 8080
app.eureka-server: eureka
spring.datasource:
  url: jdbc:mysql://mysql/review-db

spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka
